services:
    # Loki for logs
    loki:
        image: grafana/loki:latest
        container_name: loki
        ports:
            - '9101:3100'
        volumes:
            - ./loki-config.yaml:loki/local-config.yaml
        command: -config.file=loki/local-config.yaml
        networks:
            - lgtm
            - shared-network

    # Prometheus for metrics
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - '9102:9090'
        volumes:
            - ./prometheus.yml:prometheus/prometheus.yml
        command: --config.file=prometheus/prometheus.yml
        environment:
            - PROMETHEUS_TARGET=${PROMETHEUS_TARGET}
            - PROMETHEUS_JOB_NAME=${PROMETHEUS_JOB_NAME}
        networks:
            - lgtm

    # Tempo for traces
    tempo:
        image: grafana/tempo:latest
        container_name: tempo
        ports:
            - '9103:3200'
            - '4317:4317'
            - '4318:4318'
        volumes:
            - ./tempo-config.yaml:tempo.yaml
        command: -config.file=tempo.yaml
        networks:
            - lgtm

    # Grafana for visualization
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - '9110:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        depends_on:
            - loki
            - prometheus
            - tempo
        networks:
            - lgtm

volumes:
    grafana-storage:

networks:
    lgtm:
    shared-network:
        driver: bridge
